
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvozvvmpisvtmetrzetl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2b3p2dm1waXN2dG1ldHJ6ZXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjA5NTYsImV4cCI6MjA2MzIzNjk1Nn0.AxMYPkrhOAGfjGW2dIdp-duILTaCebRzigtUScFPcMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
